config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/bsc-wdc/compss:
      branch: stable
      repo: https://github.com/bsc-wdc/compss
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/bsc-wdc/compss git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-viridian-dane.sh
        container: qc.acc_muzzy-turquoise-squirrel
  QC.Doc:
    repos:
      github.com/bsc-wdc/compss find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-cornflower-beaver.sh
        container: qc.doc_geeky-brown-caterpillar
      github.com/bsc-wdc/compss git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-sangria-owl.sh
        container: qc.doc_cozy-chartreuse-avocet
      github.com/bsc-wdc/compss markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-puce-moorhen.sh
        container: qc.doc_frumpy-cyan-iguana
      github.com/bsc-wdc/compss restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-bronze-axolotl.sh
        container: qc.doc_woolly-champagne-opossum
  QC.Lic:
    repos:
      github.com/bsc-wdc/compss licensee:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-peach-monkey.sh
        container: qc.lic_bumpy-brown-starfish
  QC.Sec:
    repos:
      github.com/bsc-wdc/compss bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-persimmon-moorhen.sh
        container: qc.sec_boozy-rose-ray
  QC.Sty:
    repos:
      github.com/bsc-wdc/compss checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-wisteria-squid.sh
        container: qc.sty_hazy-indigo-mau
      github.com/bsc-wdc/compss flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-sapphire-capuchin.sh
        container: qc.sty_woozy-tomato-pinscher
      github.com/bsc-wdc/compss hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-beige-chihuahua.sh
        container: qc.sty_snippy-sangria-akita
      github.com/bsc-wdc/compss jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-emerald-iguana.sh
        container: qc.sty_scummy-mauve-dachshund
  QC.Ver:
    repos:
      github.com/bsc-wdc/compss get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-celadon-audemer.sh
        container: qc.ver_shaggy-flax-coati
timeout: 5400
