config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/bsc-wdc/compss:
      branch: stable
      repo: https://github.com/bsc-wdc/compss
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/bsc-wdc/compss git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-celadon-dhole.sh
        container: qc.acc_skinny-chocolate-gopher
  QC.Doc:
    repos:
      github.com/bsc-wdc/compss find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-ecru-ostrich.sh
        container: qc.doc_bumpy-seashell-devil
      github.com/bsc-wdc/compss git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-bronze-owl.sh
        container: qc.doc_chewy-yellow-donkey
      github.com/bsc-wdc/compss markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-turquoise-robin.sh
        container: qc.doc_cheeky-denim-guppy
      github.com/bsc-wdc/compss restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-persimmon-chamois.sh
        container: qc.doc_breezy-wisteria-moorhen
  QC.Lic:
    repos:
      github.com/bsc-wdc/compss licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-periwinkle-chamois.sh
        container: qc.lic_goopy-lavender-fossa
  QC.Met:
    repos:
      github.com/bsc-wdc/compss cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-orchid-coati.sh
        container: qc.met_wiggy-gamboge-barb
  QC.Sec:
    repos:
      github.com/bsc-wdc/compss bandit:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-black-wombat.sh
        container: qc.sec_snappy-copper-discus
  QC.Sty:
    repos:
      github.com/bsc-wdc/compss checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-champagne-koala.sh
        container: qc.sty_grumpy-grey-cuttlefish
      github.com/bsc-wdc/compss flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cinnabar-orangutan.sh
        container: qc.sty_lovely-saffron-okapi
      github.com/bsc-wdc/compss hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-alizarin-cuscus.sh
        container: qc.sty_stuffy-alizarin-moose
      github.com/bsc-wdc/compss jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-wheat-schnauzer.sh
        container: qc.sty_frumpy-ruby-shrew
  QC.Ver:
    repos:
      github.com/bsc-wdc/compss get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-salmon-gerbil.sh
        container: qc.ver_greasy-firebrick-macaque
timeout: 5400
