config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/bsc-wdc/compss:
      branch: stable
      repo: https://github.com/bsc-wdc/compss
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/bsc-wdc/compss git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-salmon-insect.sh
        container: qc.acc_wheezy-sapphire-ibis
  QC.Doc:
    repos:
      github.com/bsc-wdc/compss find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-myrtle-bloodhound.sh
        container: qc.doc_tacky-ochre-foxhound
      github.com/bsc-wdc/compss git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-myrtle-beagle.sh
        container: qc.doc_sleepy-ochre-dog
      github.com/bsc-wdc/compss markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-puce-moth.sh
        container: qc.doc_tacky-burgundy-tzu
      github.com/bsc-wdc/compss restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-corn-javanese.sh
        container: qc.doc_lumpy-denim-bracke
  QC.Lic:
    repos:
      github.com/bsc-wdc/compss licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-heliotrope-bird.sh
        container: qc.lic_whiny-purple-scorpion
  QC.Sec:
    repos:
      github.com/bsc-wdc/compss bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ready-asparagus-leopard.sh
        container: qc.sec_cozy-xanthic-robin
  QC.Sty:
    repos:
      github.com/bsc-wdc/compss checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-rose-neanderthal.sh
        container: qc.sty_jumpy-buff-bloodhound
      github.com/bsc-wdc/compss flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-red-kangaroo.sh
        container: qc.sty_lanky-smalt-donkey
      github.com/bsc-wdc/compss hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-white-tuatara.sh
        container: qc.sty_cranky-platinum-starfish
      github.com/bsc-wdc/compss jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-heliotrope-audemer.sh
        container: qc.sty_muzzy-xanthic-lemur
  QC.Ver:
    repos:
      github.com/bsc-wdc/compss get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-denim-penguin.sh
        container: qc.ver_shabby-tangerine-grasshopper
timeout: 5400
